"""Read/write/diff for ``config/manifest.yaml``.

The manifest is the committed source of truth for the inventory.
Writes are deterministic so PR diffs reflect real changes only.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

INVENTORY_KEYS = ("configs", "functions", "routes", "scripts", "skills")
TOP_LEVEL_ORDER = (
    "generated_at",
    "generator_version",
    "manifest_version",
    *INVENTORY_KEYS,
)
GENERATOR_VERSION = "1.0.0"
MANIFEST_VERSION = 1
HEADER = (
    "# AUTO-GENERATED by integrity Plugin E (config_registry).\n"
    "# Do not edit by hand — re-run `make integrity-config` after intended changes.\n"
    "# See docs/superpowers/specs/2026-04-17-integrity-plugin-e-design.md.\n"
)


@dataclass(frozen=True)
class ManifestDelta:
    added: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    removed: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    changed: dict[str, list[dict[str, Any]]] = field(default_factory=dict)


def empty_manifest() -> dict[str, Any]:
    """Empty manifest skeleton with all required keys present."""
    m: dict[str, Any] = {
        "generated_at": "",
        "generator_version": GENERATOR_VERSION,
        "manifest_version": MANIFEST_VERSION,
    }
    for key in INVENTORY_KEYS:
        m[key] = []
    return m


def read_manifest(path: Path) -> dict[str, Any]:
    """Load manifest from ``path``; returns ``empty_manifest()`` if absent."""
    if not path.exists():
        return empty_manifest()
    raw = yaml.safe_load(path.read_text()) or {}
    out = empty_manifest()
    for key in TOP_LEVEL_ORDER:
        if key in raw:
            out[key] = raw[key]
    return out


def manifest_to_yaml(manifest: dict[str, Any]) -> str:
    """Render ``manifest`` to deterministic YAML text (with header).

    Top-level keys emit in fixed order (`TOP_LEVEL_ORDER`); list entries
    sort by ``id`` ascending; LF line endings; trailing newline.
    """
    sorted_manifest = empty_manifest()
    for key in TOP_LEVEL_ORDER:
        if key in manifest:
            value = manifest[key]
            if key in INVENTORY_KEYS and isinstance(value, list):
                value = sorted(value, key=lambda e: str(e.get("id", "")))
            sorted_manifest[key] = value

    body = yaml.safe_dump(
        sorted_manifest,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=10_000,
    )
    return HEADER + body


def write_manifest(path: Path, manifest: dict[str, Any]) -> None:
    """Write ``manifest`` to ``path`` deterministically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(manifest_to_yaml(manifest))


def emit_manifest_text(repo_root: Path) -> str:
    """Re-run Plugin E against ``repo_root`` and return the regenerated YAML.

    Used by Plugin F autofix to propose a regenerated manifest without
    writing to disk. Lazy-imports ConfigRegistryPlugin to avoid circular
    import (plugin.py imports from this module).
    """
    from ...protocol import ScanContext
    from ...schema import GraphSnapshot
    from .plugin import ConfigRegistryPlugin

    plugin = ConfigRegistryPlugin(check_only=True)
    ctx = ScanContext(repo_root=repo_root, graph=GraphSnapshot.load(repo_root))
    failures: list[str] = []
    manifest = plugin.build_current(ctx, failures)
    return manifest_to_yaml(manifest)


def diff_manifests(
    current: dict[str, Any], prior: dict[str, Any]
) -> ManifestDelta:
    """Compute per-key add/remove/change between two manifests.

    ``generated_at`` and ``generator_version`` are excluded from the diff.
    Within each inventory key, entries are matched by ``id``.
    """
    added: dict[str, list[dict[str, Any]]] = {}
    removed: dict[str, list[dict[str, Any]]] = {}
    changed: dict[str, list[dict[str, Any]]] = {}

    for key in INVENTORY_KEYS:
        cur = {e["id"]: e for e in current.get(key, [])}
        pri = {e["id"]: e for e in prior.get(key, [])}
        added[key] = [cur[i] for i in sorted(cur.keys() - pri.keys())]
        removed[key] = [pri[i] for i in sorted(pri.keys() - cur.keys())]
        changed[key] = [
            {"id": i, "prior": pri[i], "current": cur[i]}
            for i in sorted(cur.keys() & pri.keys())
            if cur[i] != pri[i]
        ]

    return ManifestDelta(added=added, removed=removed, changed=changed)
